apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: guestplaybook
spec:
  replicas: 3
  selector:
    matchLabels:
      name: redis-pod
      app: guestplaybook
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: guestplaybook
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379