apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: guestplaybook
    tier: frontend
spec:
  type: Loadbalancer
  selector:
    app: guestplaybook
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000