apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: guestplaybook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestplaybook
      tier: frontend
  template:
    metadata:
      name: webapp-pod
      labels:
        app: guestplaybook
        tier: frontend
    spec:
      containers:
      - name: webapp
        image: gcr.io/google-samples/gb-frontend:v4
        ports:
        - containerPort: 80